title: Xiaoxu Yang's Homepage
page-top-title: Xiaoxu Yang's Homepage
top-section-bg-text: This is me trying...
home-subtitle: Xiaoxu Yang | 杨晓旭
copyright-text: '&copy; Xiaoxu Yang 2023-2026. All Rights Reserved.'
